site_name: components/velero
site_url: https://platform.karavel.io/components/velero
repo_name: karavel-io/platform-component-velero
repo_url: https://github.com/karavel-io/platform-component-velero
copyright: © 2021 The Karavel Project | Documentation distributed under CC BY SA 4.0
strict: false
theme:
  name: material
  palette:
    scheme: slate
markdown_extensions:
  - meta
  - footnotes
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
nav:
  - Overview: index.md
  - 1.0:
    - 1.0/configuration.md
  - 1.1:
    - 1.1/configuration.md
  - 1.2:
    - 1.1/configuration.md
