{{- if .Values.credentialsSecret.key }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "velero.name" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "velero.labels" . | nindent 4 }}
spec:
  {{- with .Values.credentialsSecret}}
  secretStoreRef:
    name: {{ .store.name }}
    kind: {{ .store.kind }}
  data:
    - secretKey: cloud
      remoteRef:
        key: {{ .key }}
        property: {{ .property }}
  {{- end }}
{{- end }}
