name: Lint
on:
  push:
    branches:
      - '*'
  pull_request: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/helmpack/chart-testing:v3.3.1
    steps:
      - uses: actions/checkout@v2
      - name: Lint component charts
        run: ct lint --charts chart

